services:
  intuitive_db:
    container_name: intuitive-db
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: root
      POSTGRES_DB: db_intuitive
    ports:
      - "5433:5432"
    volumes:
      - intuitive_db:/var/lib/postgresql/data
    networks:
      intuitive_network:

volumes:
  intuitive_db:
networks:
  intuitive_network:
